### ISSUE TITLE
Selections from anywhere on the page are returned in getSelection

### ISSUE THREAD

**Issue by solsson** [simonsoft/uniteditor-textparagraph#1]
See https://github.com/simonsoft/authormodel/commit/ccbf3246e362701bf344ce7354d2d38b428e4e57

To work with these interface specs from authormodle, link or clone that repo to node_modules/authormodel. Push to both.

**Comment by batista** [comment]
@solsson, the insertion of a `<label>` inline element in the context of text paragraph doesn't make much sense for two reasons:
1. It is being inserted as `text` and not as `html` (see [render()](https://github.com/simonsoft/uniteditor-textparagraph/blob/master/src/TextParagraphEditorBackbone.js#L47));
2. When changing the `render()` method to insert as `html`, I've faced issues with rangy selection, as it apparently can't be initiated in the parent element if there is no selection started in there. (makes sense IMO).
